import Head from 'next/head';
import Header from '../components/Header';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-5xl text-center font-medium m-20">
				Project Movie App
			</h1>
			<h2 className="text-4xl text-center font-medium m-20  text-red-500 dark:text-blue-500">
				Project Movie App
			</h2>
		</>
	);
}
